project:
  type: website
  output-dir: docs

website:
  title: ""
  description: "Um mini-curso completo sobre modelagem estatística e machine learning"
  navbar:
    left:
      - text: "Início"
        href: "#topo"
      - text: "Conteúdo"
        href: "#modulos"
      - text: "Pré-requisitos"
        href: "#requisitos"
      - text: "Inscreva-se"
        href: "#formulario"
      - text: "Sobre"
        href: "#sobre"
  page-footer:
    left: "© 2025 Caio Velasco"
    right: "Construído com ❤️ e Quarto"

format:
  html:
    theme: flatly    # cosmo or litera, simplex, flatly for readability
    smooth-scroll: false
    css: styles.css